<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_610d38cd82de4',
	'title' => 'Fees page',
	'fields' => array(
		array(
			'key' => 'field_610d38f5507d0',
			'label' => 'Wallet fees',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6110fb2161752',
			'label' => 'Wallet fees',
			'name' => 'wallet_fees',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_610d3919507d1',
					'label' => 'First section content',
					'name' => 'first_section_content',
					'type' => 'flexible_content',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layouts' => array(
						'layout_610d3c74124e9' => array(
							'key' => 'layout_610d3c74124e9',
							'name' => 'content_layout',
							'label' => 'Content',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_610d3cae5cae9',
									'label' => 'Text content',
									'name' => 'text_content',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
								),
							),
							'min' => '',
							'max' => '',
						),
						'layout_610d409cc4baf' => array(
							'key' => 'layout_610d409cc4baf',
							'name' => 'table_layout',
							'label' => 'Table',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_6110fef09a5dd',
									'label' => 'Table group',
									'name' => 'table_group',
									'type' => 'group',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_610d438d61626',
											'label' => 'Table title',
											'name' => 'table_title',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
										array(
											'key' => 'field_610d3d055caea',
											'label' => 'Table',
											'name' => 'table',
											'type' => 'repeater',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'collapsed' => '',
											'min' => 0,
											'max' => 0,
											'layout' => 'table',
											'button_label' => '',
											'sub_fields' => array(
												array(
													'key' => 'field_610d3d175caeb',
													'label' => 'Coin',
													'name' => 'coin',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array(
													'key' => 'field_610d3d295caec',
													'label' => 'Min transaction',
													'name' => 'min_transaction',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array(
													'key' => 'field_610d40315caed',
													'label' => 'Max transaction',
													'name' => 'max_transaction',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array(
													'key' => 'field_610d40585caee',
													'label' => 'Max / Day',
													'name' => 'max__day',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array(
													'key' => 'field_610d40605caef',
													'label' => 'Max / Month',
													'name' => 'max__month',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
											),
										),
										array(
											'key' => 'field_610d42f7079a3',
											'label' => 'Table description',
											'name' => 'table_description',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '* Limits are in USD. The limits above are shown in GBP and EUR for convenience.',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
										array(
											'key' => 'field_610d4318079a4',
											'label' => 'Limits',
											'name' => 'limits',
											'type' => 'repeater',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'collapsed' => '',
											'min' => 0,
											'max' => 0,
											'layout' => 'table',
											'button_label' => '',
											'sub_fields' => array(
												array(
													'key' => 'field_610d436a079a5',
													'label' => 'Limit',
													'name' => 'limit',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
											),
										),
									),
								),
							),
							'min' => '',
							'max' => '',
						),
					),
					'button_label' => 'Add',
					'min' => '',
					'max' => '',
				),
				array(
					'key' => 'field_610d43bf61627',
					'label' => 'Bullits',
					'name' => 'bullits',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Add bullit',
					'sub_fields' => array(
						array(
							'key' => 'field_610d43fa61628',
							'label' => 'Bullit title',
							'name' => 'bullit_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '100',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_610d442661629',
							'label' => 'Bullit content',
							'name' => 'bullit_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '100',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
				),
				array(
					'key' => 'field_610d44606162a',
					'label' => 'Ethereum transactions section title',
					'name' => 'ethereum_transactions_section',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Ethereum transactions',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_610d44ca6162b',
					'label' => 'Ethereum transactions content',
					'name' => 'ethereum_tran',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'In order to enhance your assets security, eToro wallet is a multi-signature wallet, using smart contracts for Ethereum. Unfortunately, not all wallet providers and exchanges support sending and receiving via smart contracts. Please make sure you know the address provider on the receiving side supports ETH transactions sent from multi-signature addresses. If there are issues encountered the receiving party’s provider needs to be contacted.

Wallet creation fees (including any discounts) are subject to change at any given time and could change on a daily basis. We encourage you to visit this page periodically to stay updated on current fees.',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array(
					'key' => 'field_610e36f882e1c',
					'label' => 'Ethereum transactions assets',
					'name' => 'ethereum_transactions_assets',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => 'Add asset',
					'sub_fields' => array(
						array(
							'key' => 'field_610e374a82e1d',
							'label' => 'Asset short name',
							'name' => 'asset_short_name',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'templates/fees-page.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;

?>